server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scoreboard
    username: 'postgres'
    password: 'postgres'
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: db/changelog/db.changelog-master.xml

